parameters:
#    eliecer_simulacion.example.class: Eliecer\SimulacionBundle\Example

services:
#    eliecer_simulacion.example:
#        class: %eliecer_simulacion.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
